defaults:
  - _self_
  - data_config
  - training_config
  - experiment_config
  - ncns_config
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .