#experiment_conifg.yaml
experiment_config:
  checkpoint_path: lightning_checkpoints
  run_name: null
  save_dir: ./mlruns

  accelerator: cpu
  devices: 1
  precision: 32
  enable_progress_bar: true
  progress_refresh_rate: 10
  seed: 123

  log_every_n_steps: 1
  check_eval_n_epoch: 1
  num_sanity_val_steps: 0
  # check_metrics_n_epoch: 10